rand "1" "10" =hidden.number=;
let "lifes" "3";
let "status" "guess the number!";
:loop;
clear;
text "0" "100" "#FFCC00" "140" "=== GUESS THE NUMBER ===";
concat "lifes : " "!lifes" "txt_lifes";
text "0" "50" "#FFFFFF" "100" "!txt_lifes";
text "0" "10" "#00FFFF" "90" "!status";
input "your guess (1 to 10): " "input";
goto "won" "equal" "!input" "!hidden.number";
sub -!lifes- -1- =lifes=;
goto "lost.life" "always" "0" "0";
:lost.life;
goto "game.over" "equal" "!lifes" "0";
let "status" "wrong! try again.";
goto "loop" "always" "0" "0";
:won;
clear;
text "0" "50" "#00FF00" "160" "you won!";
concat "the number was: " "!hidden.number" "end.msg";
text "0" "0" "#FFFFFF" "100" "!end.msg";
goto "end" "always" "0" "0";
:game.over;
clear;
text "0" "50" "#FF3333" "160" "GAME OVER!";
concat "the number was: " "!hidden.number" "end.msg";
text "0" "0" "#FFFFFF" "100" "!end.msg";
goto "end" "always" "0" "0";
:end;
exit "game ended.";
